channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.10.0
  - cffi==1.15.1
  - click==8.0.4
  - cloudpickle==2.2.1
  - cytoolz==0.12.0
  - defusedxml==0.7.1
  - distributed==2023.6.0
  - importlib-metadata==6.0.0
  - jinja2==3.1.2
  - lightgbm==4.2.0
  - lz4==4.3.2
  - matplotlib==3.8.1
  - numpy==1.24.3
  - packaging==23.1
  - pandas==2.0.3
  - pathlib==1.0.1
  - pyarrow==11.0.0
  - python-snappy==0.6.1
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.11.1
  - xxhash==2.0.2
  - zstandard==0.19.0
name: mlflow-env
