name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run tests
          run: |
            pytest
  deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Deploy to Heroku
            uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
            with:
              heroku_api_key: ${{HEROKU_API_KEY}}
              heroku_app_name:  ${{ HEROKU_APP_NAME }}
              heroku_email: ${{ HEROKU_EMAIL }}
